swagger: "2.0"
info:
  title: Device register API
  version: 1.0.1
  description: API documentation for device register application.

tags:
  - name: Devices
    description: API endpoints related to devices
  - name: Classes
    description: API endpoints related to device classes
  - name: Events
    description: API endpoints related to events
  - name: Users
    description: API endpoints related to users
  - name: Authentication
    description: API endpoints related to authentication
  - name: Attachments
    description: API endpoints related to attachments

paths:
  /devices/:
    get:
      tags:
        - Devices
      summary: Get all devices
      parameters:
        - in: header
          name: Authorization
          description: Bearer format
          required: false
          type: string
      responses:
        '200':
          description: A list of devices
          schema:
            type: array
            items:
              $ref: '#/definitions/Device'
    post:
      tags:
        - Devices
      summary: Add new devices
      parameters:
        - in: header
          name: Authorization
          description: Bearer format
          required: false
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/NewDevice'
            example:
              - dev_name: "Device 1"
                dev_model: "Model 1"
                class_id: 1
                dev_manufacturer: "Company 1"
                dev_comments: "Some comments"
                dev_home: "Some home"
                dev_location: "Room 101"
              - dev_name: "Device 2"
                dev_model: "Model 2"
                class_id: 1
                dev_manufacturer: "Company 2"
                dev_comments: "Some comments"
                dev_home: "Some home"
                dev_location: "Room 102"
      responses:
        '201':
          description: Devices created
        '400':
          description: Invalid input
        '500':
          description: Database error
    delete:
      tags:
        - Devices
      summary: Delete devices
      security:
        - bearerAuth: [ ]
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: array
            items:
              type: object
              properties:
                id:
                  type: integer
            example:
              - id: 2
              - id: 3

      responses:
        '200':
          description: Devices deleted
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Devices not found
        '500':
          description: Database error

  /devices/{dev_id}:
    get:
      tags:
        - Devices
      summary: Get device by ID
      parameters:
        - name: dev_id
          in: path
          required: true
          type: integer
        - in: header
          name: Authorization
          description: Bearer format
          required: false
          type: string
      responses:
        '200':
          description: A single device
          schema:
            $ref: '#/definitions/Device'
        '404':
          description: Device not found

    patch:
      tags:
          - Devices
      summary: Update device by ID
      security:
        - bearerAuth: [ ]
      parameters:
      - name: dev_id
        in: path
        required: true
        type: integer
      - in: body
        name: body
        required: true
        schema:
          type: array
          items:
            type: object
            properties:
              class_id:
                type: integer
                example: 1
              dev_comments:
                type: string
                example: "Some comments"
              dev_home:
                type: string
                example: "Some specific place"
              dev_name:
                type: string
                example: "Device 1"
              dev_manufacturer:
                type: string
                example: "Company 1"
              dev_model:
                type: string
                example: "Model 1"
      responses:
          '200':
            description: Device updated
          '400':
            description: Invalid input
          '401':
            description: Unauthorized
          '404':
            description: Device not found
          '500':
            description: Database error

  /devices/{dev_id}/events:
    get:
      tags:
        - Devices
      summary: Get all events for device
      parameters:
        - name: dev_id
          in: path
          required: true
          type: integer
        - in: header
          name: Authorization
          description: Bearer format
          required: false
          type: string
      responses:
        '200':
          description: A list of events
          schema:
            type: array
            items:
              $ref: '#/definitions/EventWithoutUserEmail'
        '404':
          description: Device not found

  /devices/current_locations:
    get:
      tags:
        - Devices
      summary: Get current locations of all devices
      parameters:
        - in: header
          name: Authorization
          description: Bearer format
          required: false
          type: string
      responses:
        '200':
          description: List of devices with current locations
          schema:
            type: array
            items:
              type: object
              properties:
                dev_id:
                  type: integer
                  example: 1
                dev_name:
                  type: string
                  example: "Device 1"
                dev_manufacturer:
                  type: string
                  example: "Company 1"
                dev_model:
                  type: string
                  example: "Model 1"
                loc_name:
                  type: string
                  example: "Room 101"
                move_time:
                  type: string
                  format: date-time
                  example: "2024-12-11T11:11:11"
                class_name:
                  type: string
                  example: "Säädin"
        '500':
          description: Database error

  /devices/import:
    post:
      tags:
        - Devices
      summary: "Create devices by uploading a CSV"
      description: |
        Allows creating devices by uploading a CSV file that contains device info separated by semicolon.
        CSV header (first line) should be:
        dev_name;dev_manufacturer;dev_model;dev_home;dev_class;dev_comments;dev_location
      security:
        - bearerAuth: [ ]
      parameters:
        - name: "files"
          in: "formData"
          description: "CSV to be uploaded"
          required: true
          type: "file"
      consumes:
        - "multipart/form-data"
      responses:
        201:
          description: Devices created
        400:
          description: Bad request - no csv file or wrong format
        500:
          description: Internal server error

  /devices/export:
    get:
      tags:
        - Devices
      summary: "Export devices in csv format compatible with import"
      description: |
        Exports database devices in csv format:
        dev_name;dev_manufacturer;dev_model;dev_home;dev_class;dev_comments;dev_location
      security:
        - bearerAuth: [ ]
      responses:
        500:
          description: Internal server error


  /users/:
    get:
      tags:
        - Users
      summary: Get all users
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: A list of users
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
        '401':
          description: Unauthorized

  /users/{user_id}:
    get:
      tags:
        - Users
      summary: Get user by ID
      security:
        - bearerAuth: [ ]
      parameters:
        - name: user_id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: A single user
          schema:
            $ref: '#/definitions/User'
        '401':
          description: Unauthorized
        '404':
          description: User not found

  /events/:
    get:
      tags:
        - Events
      summary: Get all events
      security:
        - bearerAuth: [ ]
      responses:
        '200':
          description: A list of events
          schema:
            type: array
            items:
              allOf:
                - $ref: '#/definitions/Event'
                - type: object
                  properties:
                    dev_name:
                      type: string
                      example: "Device A"
                    user_name:
                      type: string
                      example: "Nimi Niminen"
                    user_email:
                      type: string
                      example: "nimi.niminen@sahkoposti.com"
        '401':
          description: Unauthorized
    post:
      tags:
        - Events
      summary: Add new events
      parameters:
        - in: header
          name: Authorization
          description: Bearer format
          required: false
          type: string
        - in: body
          name: body
          required: true
          schema:
            type: array
            items:
              $ref: '#/definitions/NewEvent'
            example:
              - dev_id: 1
                move_time: "2024-12-11 11:11:11"
                loc_name: "Room123"
                company: "Teknologiafirma"
                comment: "Move"
                user:
                  user_name: "Siirtäjä"
                  user_email: "Siirtäjä@example.com"
              - dev_id: 2
                move_time: "2024-12-12 12:12:12"
                loc_name: "Room345"
                company: "Toinen firma"
                comment: "Move2"
                user:
                  user_name: "Päällikkö"
                  user_email: "Päällikkö@example.com"

      responses:
        '201':
          description: Events created
        '400':
          description: Invalid input
        '500':
          description: Database error

  /events/{event_id}:
    get:
      tags:
        - Events
      summary: Get event by ID
      security:
        - bearerAuth: [ ]
      parameters:
        - name: event_id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: A single event
          schema:
            $ref: '#/definitions/Event'
        '401':
          description: Unauthorized
        '404':
          description: Event not found
    delete:
      tags:
        - Events
      summary: Delete event by ID
      security:
        - bearerAuth: [ ]
      parameters:
        - name: event_id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: Event deleted
        '401':
          description: Unauthorized
        '404':
          description: Event not found

    patch:
      tags:
        - Events
      summary: Update event by ID
      security:
        - bearerAuth: [ ]
      parameters:
      - name: event_id
        in: path
        required: true
        type: integer
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/NewEvent'
      responses:
        '200':
          description: Event updated
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '404':
          description: Event not found
        '500':
          description: Database error

  /classes/:
    get:
      tags:
        - Classes
      summary: Get all classes
      parameters:
        - in: header
          name: Authorization
          description: Bearer format
          required: false
          type: string
      responses:
        '200':
          description: List of classes
          schema:
            type: array
            items:
              $ref: '#/definitions/Class'
    post:
      tags:
        - Classes
      summary: Create new class
      security:
        - bearerAuth: [ ]
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/NewClass'
      responses:
        '201':
          description: Class created
        '400':
          description: Invalid input
        '401':
          description: Unauthorized
        '409':
          description: Class already exists
        '500':
          description: Database error


  /classes/{class_id}:
    delete:
      tags:
        - Classes
      summary: Delete class by ID
      security:
        - bearerAuth: [ ]
      parameters:
        - name: class_id
          in: path
          required: true
          type: integer
      responses:
        '200':
          description: Class deleted
        '401':
          description: Unauthorized
        '404':
          description: Class not found
        '409':
          description: Class cannot be deleted due to foreign key constraint. The class is still used by a device.
        '500':
          description: Database error


  /attachments/upload/{dev_id}:
    post:
      tags:
        - Attachments
      summary: "Upload attachments for device"
      description: "Allows uploading one or more attachments (PDF, PNG, JPEG) for device."
      parameters:
        - name: "dev_id"
          in: "path"
          required: true
          type: "integer"
        - in: header
          name: Authorization
          description: Bearer format
          required: false
          type: string
        - name: "files"
          in: "formData"
          description: "File(s) to be uploaded"
          required: true
          type: "file"
          x-multiple: true
      consumes:
        - "multipart/form-data"
      responses:
        200:
          description: "Files uploaded successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Files uploaded successfully"
              files:
                type: "array"
                items:
                  type: "string"
                  example: "example.pdf"
        400:
          description: "Bad request - no files or invalid file type"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "No files uploaded"
        404:
          description: "Device not found"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Device not found"
        500:
          description: "Internal server error"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Failed to create directory or save file"

  /attachments/list/{dev_id}:
    get:
      tags:
        - Attachments
      summary: "List attachments for device"
      description: "Lists all attachments for device."
      parameters:
        - name: "dev_id"
          in: "path"
          required: true
          type: "integer"
        - in: header
          name: Authorization
          description: Bearer format
          required: false
          type: string
      responses:
        200:
          description: "List of attachments"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "Files retrieved successfully"
              files:
                type: "array"
                items:
                  type: "string"
                  example: "/static/attachments/1/example.pdf"
        404:
          description: "Directory not found"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Directory not found"
        500:
          description: "Internal server error"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Failed to read directory"


  /attachments/delete/{dev_id}/{file_name}:
    delete:
      summary: "Delete a specific attachment file for a device"
      description: "Deletes attachment from specified device."
      security:
        - bearerAuth: [ ]
      tags:
        - "Attachments"
      parameters:
        - name: "dev_id"
          in: "path"
          required: true
          type: "integer"
        - name: "file_name"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "File deleted successfully"
          schema:
            type: "object"
            properties:
              message:
                type: "string"
                example: "File deleted successfully"
        "401":
          description: "Unauthorized access, admin privileges required"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Unauthorized access"
        "404":
          description: "Directory or file not found"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Directory not found or File not found in the directory"
        "500":
          description: "Failed to delete the file due to server error"
          schema:
            type: "object"
            properties:
              error:
                type: "string"
                example: "Failed to delete the file"
              details:
                type: "string"
                example: "Detailed error message"

  /auth/login:
    post:
      tags:
        - Authentication
      summary: "Admin login"
      description: "Logs in as an admin to receive a JWT token."
      consumes:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Bearer format
          required: false
          type: string
        - in: body
          name: credentials
          description: "Admin login credentials"
          required: true
          schema:
            type: object
            properties:
              username:
                type: string
                example: "admin"
              password:
                type: string
                example: "admin"
      responses:
        200:
          description: "Successful login"
          schema:
            type: object
            properties:
              access_token:
                type: string
                description: "JWT token for accessing protected endpoints"
        401:
          description: "Unauthorized - Invalid credentials"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Invalid credentials"

  /auth/admin:
    get:
      tags:
        - Authentication
      summary: "Admin authorization check"
      description: "Checks if the logged-in user is authorized as an admin."
      security:
        - bearerAuth: [ ]
      responses:
        200:
          description: "Authorized"
          schema:
            type: object
            properties:
              message:
                type: string
                example: "Authorized"
        403:
          description: "Forbidden - User is not authorized"
          schema:
            type: object
            properties:
              error:
                type: string
                example: "Unauthorized"

securityDefinitions:
    bearerAuth:
        type: apiKey
        name: Authorization
        in: header
        description: "Enter 'Bearer <JWT>' to authorize. Example: 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...'"

definitions:
  Device:
    type: object
    properties:
      dev_id:
        type: integer
      dev_name:
        type: string
      dev_manufacturer:
        type: string
      dev_model:
        type: string
      dev_home:
        type: string
      class_name:
        type: string
      dev_comments:
        type: string
    example:
        dev_id: 1
        dev_name: "Hienosäädin"
        dev_manufacturer: "TAMK"
        dev_model: "Mahtava malli"
        dev_home: "Laitteen koti"
        class_name: "Säädin"
        dev_comments: "Tosi hyvä laite"

  NewDevice:
    type: object
    properties:
      dev_name:
        type: string
      dev_manufacturer:
        type: string
      dev_model:
        type: string
      dev_home:
        type: string
      class_id:
        type: integer
      dev_comments:
        type: string
      dev_location:
        type: string
    example:
      dev_name: "Hienosäädin"
      dev_manufacturer: "TAMK"
      dev_model: "Mahtava malli"
      dev_home: "Laitteen koti"
      class_id: 1
      dev_comments: "Tosi hyvä laite"
      dev_location: "Room 101"

  User:
    type: object
    properties:
      user_id:
        type: integer
      user_name:
        type: string
      user_email:
        type: string

  NewUser:
    type: object
    properties:
      user_name:
        type: string
      user_email:
        type: string

  Event:
    type: object
    properties:
      event_id:
        type: integer
        example: 1
      dev_id:
        type: integer
        example: 2
      move_time:
        type: string
        format: date-time
        example: "2024-12-11T11:11:11"
      loc_name:
        type: string
        example: "Room 101"
      user_id:
        type: integer
        example: 1
      user_name:
        type: string
        example: "Testi Testinen"
      user_email:
        type: string
        example: "email@email.com"
      company:
        type: string
        example: "Oy Firma Ab"
      comment:
        type: string
        example: "Rikki"

  NewEvent:
    type: object
    properties:
      dev_id:
        type: integer
        example: 1
      move_time:
        type: string
        format: date-time
        example: "2024-12-11 11:11:11"
      loc_name:
        type: string
      company:
        type: string
      comment:
        type: string
      user:
        $ref: '#/definitions/NewUser'

  EventWithoutUserEmail:
    type: object
    properties:
      event_id:
        type: integer
        example: 1
      dev_id:
        type: integer
        example: 1
      move_time:
        type: string
        format: date-time
        example: "2024-12-11T11:11:11"
      loc_name:
        type: string
        example: "Room 101"
      company:
        type: string
        example: "Firma Oy"
      comment:
        type: string
        example: "Routine maintenance performed"
      user_id:
        type: integer
        example: 1
      user_name:
        type: string
        example: "Testi Testinen"

  Class:
    type: object
    properties:
      class_id:
        type: integer
      class_name:
        type: string
    example:
        class_id: 1
        class_name: "Lentokone"

  NewClass:
    type: object
    properties:
      class_name:
        type: string
    example:
      class_name: "Kamera"

